name: action_test
on:
  push:
    branches: master
  schedule:
    - cron: '0 * * * *'
  watch:
    types: [started]
jobs:
  actiontest:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - run: npm install
     - name: Update
       uses: ./
       env:
          TRAKT_ID: ${{ secrets.TRAKT_ID }}
          TRAKT_USERNAME: ${{ secrets.TRAKT_USERNAME }}
