name: archive
on:
  push:
    branches: master
  schedule:
    - cron: '14 0 * * SUN'
  watch:
    types: [started]
jobs:
  actiontest:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - run: npm install
     - name: Update
       uses: ./
       env:
          TRAKT_ID: ${{ secrets.TRAKT_ID }}
          TRAKT_USERNAME: ${{ secrets.TRAKT_USERNAME }}
          WAKA_ACTIVITY_URL: ${{ secrets.WAKA_ACTIVITY_URL }}
          WAKA_URL: ${{ secrets.WAKA_URL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REDIRECT_URIS: ${{ secrets.REDIRECT_URIS }}
          GDRIVE_FOLDER: ${{ secrets.GDRIVE_FOLDER }}
